# Generated by Django 5.2.8 on 2025-12-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='Categoria',
            new_name='categoria',
        ),
        migrations.AddField(
            model_name='comentario',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='articulos/'),
        ),
    ]
